### PR TITLE
Testing environment for issue #5

### PR DESCRIPTION
**Pull request by brendtumi**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
Callkit windows is not op
## What is the new behavior?
Create callkit screen on pushkit request while app is not running

Implements #5 .

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi @brendtumi! I'm finally testing this PR. Sorry it took so long.

It looks like the delegate registers just fine, but I never get a token because `pushRegistryDidUpdatePushCredentialsForType` is not invoked. Do you have any suggestions perhaps?

**Comment by brendtumi** [comment]
You need an apple VOIP certificate for push token far as I know

**Comment by EddyVerbruggen** [comment]
Thanks @brendtumi, I  tried that, but I was actually wondering which one of these you've used to test this:

The one at the top **Apple Push Notification service SSL (Sandbox & Production)**, or at the bottom **Apple Push Notification service SSL (Sandbox & Production)** (I think I used the former, because it explicitly mentions it can be used for VoIP as well):

Screenshot 2019-04-30 at 16 59 20

**Comment by yerol** [comment]
Voip Services Certificate is the right one

**Pull request merged**
